### ISSUE TITLE
Could not load user data

### ISSUE THREAD

**Issue by GuitaristForEver** [OpenUnison/openunison-k8s-login-oidc#11]
HI... Im getting the atached error on Orchestra Pod when a specific user is signing in..
other users I tested is OK
[orchestra .log](https://github.com/OpenUnison/openunison-k8s-login-oidc/files/3540579/orchestra.log)

any idea why?

**Comment by GuitaristForEver** [comment]
doesn't look much different than other users on our Azure Active Directory :)

**Comment by GuitaristForEver** [comment]
Update :
I've contacted Azure support they pointed out that the user is not in the app role assignment, I'm not

 sure why. but, after I added the user manually I get a different error. here's the orchestra log

**Comment by mlbiam** [comment]
user doesn't have a `first_name`

**Comment by GuitaristForEver** [comment]
After adding the user's first name manually it works! :) 
thanks @mlbiam !
