### ISSUE TITLE
Is it possible to supply a custom certificate during installation?

### ISSUE THREAD

**Issue by dkulchinsky** [OpenUnison/openunison-k8s-login-oidc#22]
I've reviewed the steps described here https://github.com/TremoloSecurity/OpenUnison/wiki/troubleshooting#how-do-i-change-openunisons-certificates to replace the self-signed certificate with a custom one, but is it possible to do it as part of the installation to avoid extra steps?

specifically, we're using the helm chart to deploy this orchestra plugin.

Thanks!

**Comment by mlbiam** [comment]
> if I update the ingress manually, will the operator change it back?

No.  The other option is to create a `Certificate` object so you don't need to add the annotation

**Comment by dkulchinsky** [comment]
Just managed to glue this together 😄 

1. Removed the `ou-tls-certificate` `create_data` block from `orchestra`
2. added the cert-manager annotation to the ingress


I guess my only ask is to be able to add custom annotations to the generated `ingress` resource 🙏 

This method is preferred because it ensures cert-manager keeps track of all the ingresses and updates them accordingly.

**Comment by dkulchinsky** [comment]
I worked around point (2) above by creating a cert-manager `Certificate` resource that populates it in a secret that the Ingress then consumes, this seems to work well.

**Comment by mlbiam** [comment]
Our next release of the operator supports adding annotations to the ingress definition.   we'll also support disabling the creation of `ou-tls-certificate`

**Comment by dkulchinsky** [comment]
ohh, wonderful! can't wait for the next release 😄

**Comment by mlbiam** [comment]
Annotations are now supported on the `Ingress` from the Helm chart
