### ISSUE TITLE
Can't access Kubernetes Dashboard Chapter 7

### ISSUE THREAD

**Issue by kushan22** [OpenUnison/openunison-k8s-login-oidc#49]
I deployed the kubernetes dashboard and Openunison Operator by following the step by step process in Chapter 7 of the book. I can visit the openunison host but when I click on Kubernetes Dashboard I get this error.
![image](https://user-images.githubusercontent.com/14822234/128086040-752abf26-fcc0-48b1-b244-ef027c0f70bf.png)

I am not sure what the error is

**Comment by mlbiam** [comment]
What do the logs in the openunison-orchestra pod in the openunison name space say?

**Comment by mlbiam** [comment]
closing do to iniactivity
