### ISSUE TITLE
Other ingress controllers

### ISSUE THREAD

**Issue by brackend** [OpenUnison/openunison-k8s-login-oidc#51]
Hi,

is Orchestra login portal limited to Nginx?  Is it possible to install alongside Traefik ingress controller?

Thank you

**Comment by mlbiam** [comment]
It should work with Traefik.  The operator won't generate an `Ingress`, but take a look at https://github.com/OpenUnison/openunison-k8s-login-oidc/issues/44

**Comment by brackend** [comment]
Cheers thank you!   Will let you know how I get on
